version: '2'
services:
    web:
        build: .
        ports:
            - "8888:8888"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis