version: '2'

services:

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword --appendonly  yes
    ports:
      - 6379
    volumes:
      - redis:/data


  api:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" -k gevent --timeout 3600  --workers 1 --reload  "mrsservice.app:create_app()" --access-logfile access_apis.log

    volumes:
      - '.:/mrsservice'
    ports:
      - '5000:5000'
    environment:
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - CLOUDAMQP_URL=${CLOUDAMQP_URL}
      - ODOO_URL=${ODOO_URL}

  celery:
    build: .
    command: celery worker -B -l info -A mrsservice.blueprints.transaction.tasks
    command: celery worker -B -l info -A mrsservice.blueprints.webhook.tasks
    command: celery worker -B -l info -A mrsservice.blueprints.partner.tasks
    command: celery worker -B -l info -A mrsservice.blueprints.route.tasks
    environment:
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - CLOUDAMQP_URL=${CLOUDAMQP_URL}
      - ODOO_URL=${ODOO_URL}

    env_file:
      - '.env'
    volumes:
      - '.:/mrsservice'

volumes:
  redis:
  apis:
